### ISSUE TITLE
When loading mcd, the first panorama should be selected and reset to view

### ISSUE THREAD

**Issue by nilseling** [BodenmillerGroup/napari-imcreg#7]
Hey,

1. when loading the mcd file and a czi, python still throws the error 

```
PluginError: Error in plugin 'builtins', hook 'napari_get_reader'
  Cause was: ValueError('Could not find a format to read the specified file in single-image mode')
    in file: /Users/immucan/opt/anaconda3/envs/napping/lib/python3.9/site-packages/imageio/core/functions.py
    at line: 181
     author: napari team
      email: napari-steering-council@googlegroups.com
    package: napari
        url: https://napari.org
    version: 0.4.4
```

I'm not fully sure from which file type this is coming since both images can be read in.

2. For the mcd file, I think it would be good to select the first panorama by default - otherwise it can be a bit confusing to find the panorama since one needs to click the "Home" button first.

Thanks for your efforts on this!
Cheers,

Nils

**Comment by jwindhager** [comment]
Thanks for reporting

1. is known, and I fixed it with https://github.com/napari/napari/pull/2206 (will be part of napari 0.4.5, see https://github.com/napari/napari/pull/2242). Until then, just ignore :-)
2. this is a bit tricky, unfortunately, as this concerns the `napari-imc` plugin (napping merely calls `viewer.open('/path/to/file.mcd')` and doesn't care about the data type). I'm not sure whether showing the first panorama should be the default for the "general" `napari-imc`, though, as the panoramas are in arbitrary order. Opinions?

**Comment by nilseling** [comment]
Excellent!
