### ISSUE TITLE
Control points are all labelled as "1" when opening an mcd for which control points have been set

### ISSUE THREAD

**Issue by nilseling** [BodenmillerGroup/napari-imcreg#9]
Hey,

I do the following:

1. Set control points on an mcd and their counterpart on a czi.
2. I close `napping`
3. I open `napping` again
4. I select the same files for visualisation

The previously set control points are now all marked as "1"

Cheers,

Nils

**Comment by jwindhager** [comment]
Thanks for reporting

Known bug for which I don't know the solution (yet) :smile: 

The napari interface for point labels is currently being refactored, waiting for that before attempting to fix this bug.

Note that, when you add another point, the point IDs are "restored"

**Comment by jwindhager** [comment]
See https://github.com/napari/napari/issues/2115

**Comment by nilseling** [comment]
I have now noticed that when reopening the images where points have already been set, the correct points are replaced by point number 1.

**Comment by nilseling** [comment]
Maybe an "Export points" button would be a quick fix.

**Comment by jwindhager** [comment]
> I have now noticed that when reopening the images where points have already been set, the correct points are replaced by point number 1.

Ok, that's definitely a bug then

> Maybe an "Export points" button would be a quick fix.

The points are already saved automatically to the control points directory - could you maybe check the state of that file when testing next time? Thanks!

**Comment by nilseling** [comment]
That's how I know that the control points are overwritten. To me it seems like the problem comes from the fact that the control points are always and automatically written out, where erroneous points replace the correct ones.
